//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedUA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedUA.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильна пошта або користувач з такою поштовою адресою вже зареєстрован .
        /// </summary>
        public static string AccountEnterEmailError {
            get {
                return ResourceManager.GetString("AccountEnterEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з такою поштовою адресою не знайден..
        /// </summary>
        public static string AccountEnterEmailNotFound {
            get {
                return ResourceManager.GetString("AccountEnterEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний email або медичний код.
        /// </summary>
        public static string AccountRegisterCodeOrEmailIsNotValid {
            get {
                return ResourceManager.GetString("AccountRegisterCodeOrEmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        public static string AddPatientPartialButton {
            get {
                return ResourceManager.GetString("AddPatientPartialButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група крові.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити.
        /// </summary>
        public static string ChangePasswordChangePassord {
            get {
                return ResourceManager.GetString("ChangePasswordChangePassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змініть пароль.
        /// </summary>
        public static string ChangePasswordChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangePasswordChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        public static string ChangePasswordViewTitle {
            get {
                return ResourceManager.GetString("ChangePasswordViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дякую за реєстрацію в системі med.ua. Будь-ласка, перевірте вашу поштову скриньку. Якщо ваша скринька зареєстрована, ми надіслали Вам листа..
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тільки для ДЕМО: Будь-ласка, перейдіть за {0}, щоб підтвердити Вашу поштову скриньку..
        /// </summary>
        public static string ConfirmEmailMessageLinkFormat {
            get {
                return ResourceManager.GetString("ConfirmEmailMessageLinkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to цим посиланням.
        /// </summary>
        public static string ConfirmEmailMessageLinkText {
            get {
                return ResourceManager.GetString("ConfirmEmailMessageLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтверження поштової скриньки.
        /// </summary>
        public static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтверження поштової скриньки.
        /// </summary>
        public static string ConfirmLinkTitle {
            get {
                return ResourceManager.GetString("ConfirmLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити новий пароль.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої пацієнти.
        /// </summary>
        public static string DoctorLayoutMyPatient {
            get {
                return ResourceManager.GetString("DoctorLayoutMyPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук пацієнта.
        /// </summary>
        public static string DoctorLayoutSearchPatient {
            get {
                return ResourceManager.GetString("DoctorLayoutSearchPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лікарня.
        /// </summary>
        public static string DoctorProfileViewModelHospital {
            get {
                return ResourceManager.GetString("DoctorProfileViewModelHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиція.
        /// </summary>
        public static string DoctorProfileViewModelPosition {
            get {
                return ResourceManager.GetString("DoctorProfileViewModelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний email або пароль.
        /// </summary>
        public static string DoctorRegisterControllerLoginInvalidAttempt {
            get {
                return ResourceManager.GetString("DoctorRegisterControllerLoginInvalidAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-адреса неправильного формату.
        /// </summary>
        public static string EmailAddressInvalidFormat {
            get {
                return ResourceManager.GetString("EmailAddressInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продовжити.
        /// </summary>
        public static string EnterMailContinue {
            get {
                return ResourceManager.GetString("EnterMailContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть email адресу, за допомогою якої Вас реєстрували в системі.
        /// </summary>
        public static string EnterMailEnterMailMessage {
            get {
                return ResourceManager.GetString("EnterMailEnterMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструйтеся.
        /// </summary>
        public static string EnterMailTitle {
            get {
                return ResourceManager.GetString("EnterMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скарги.
        /// </summary>
        public static string EntryHistoryViewModelComplains {
            get {
                return ResourceManager.GetString("EntryHistoryViewModelComplains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string EntryHistoryViewModelDate {
            get {
                return ResourceManager.GetString("EntryHistoryViewModelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основний діагноз.
        /// </summary>
        public static string EntryHistoryViewModelDiagnosis {
            get {
                return ResourceManager.GetString("EntryHistoryViewModelDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лікар.
        /// </summary>
        public static string EntryHistoryViewModelDoctorSign {
            get {
                return ResourceManager.GetString("EntryHistoryViewModelDoctorSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;єктивний стан.
        /// </summary>
        public static string EntryHistoryViewModelExamination {
            get {
                return ResourceManager.GetString("EntryHistoryViewModelExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендації.
        /// </summary>
        public static string EntryHistoryViewModelRecomendations {
            get {
                return ResourceManager.GetString("EntryHistoryViewModelRecomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дослідження.
        /// </summary>
        public static string EntryHistoryViewModelResearches {
            get {
                return ResourceManager.GetString("EntryHistoryViewModelResearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виникла помилка..
        /// </summary>
        public static string ErrorHasOccured {
            get {
                return ResourceManager.GetString("ErrorHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щось трапилось :(.
        /// </summary>
        public static string ErrorViewErrorOccurs {
            get {
                return ResourceManager.GetString("ErrorViewErrorOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під час Вашого запиту, щось пішло не так. Будь-ласка,спробуйте перезавтажити сторінку.
        /// </summary>
        public static string ErrorViewErrorOccursMessage {
            get {
                return ResourceManager.GetString("ErrorViewErrorOccursMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string ErrorViewTitle {
            get {
                return ResourceManager.GetString("ErrorViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за цим посиланням.
        /// </summary>
        public static string ForgotPasswordConfirmationLink {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тільки для ДЕМО: Будь-ласка, перейдіть за {0}, щоб встановити новий пароль..
        /// </summary>
        public static string ForgotPasswordConfirmationMessageStringFormat {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationMessageStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Ваш email був відправлений лист. Будь-ласка, перейдіть за посиланням, щоб встановити новий пароль..
        /// </summary>
        public static string ForgotPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string ForgotPasswordEmailLink {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть поштову скриньку.
        /// </summary>
        public static string ForgotPasswordEnterEmail {
            get {
                return ResourceManager.GetString("ForgotPasswordEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забули пароль?.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрати.
        /// </summary>
        public static string ListPatientsViewChoose {
            get {
                return ResourceManager.GetString("ListPatientsViewChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пацієнти.
        /// </summary>
        public static string ListPatientsViewTitle {
            get {
                return ResourceManager.GetString("ListPatientsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо не пам&apos;ятаєте Ваш email, будь-ласка, зв&apos;яжіться з менеджером: +38044-44-44-444.
        /// </summary>
        public static string LoginFooterMessage {
            get {
                return ResourceManager.GetString("LoginFooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброго вечора.
        /// </summary>
        public static string LoginPartialGoodAfternoon {
            get {
                return ResourceManager.GetString("LoginPartialGoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброго дня.
        /// </summary>
        public static string LoginPartialGoodDay {
            get {
                return ResourceManager.GetString("LoginPartialGoodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброго ранку.
        /// </summary>
        public static string LoginPartialGoodMorning {
            get {
                return ResourceManager.GetString("LoginPartialGoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброї ночі.
        /// </summary>
        public static string LoginPartialGoodNight {
            get {
                return ResourceManager.GetString("LoginPartialGoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string LoginPartialLogin {
            get {
                return ResourceManager.GetString("LoginPartialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string LoginPartialLogOff {
            get {
                return ResourceManager.GetString("LoginPartialLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перший раз?.
        /// </summary>
        public static string LoginPartialRegistrer {
            get {
                return ResourceManager.GetString("LoginPartialRegistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string LoginPartialSettings {
            get {
                return ResourceManager.GetString("LoginPartialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string LoginViewLogin {
            get {
                return ResourceManager.GetString("LoginViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Використовуйте Ваш email, який ви вказували для реєстрації..
        /// </summary>
        public static string LoginViewMessage {
            get {
                return ResourceManager.GetString("LoginViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійдіть.
        /// </summary>
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змініть налаштування.
        /// </summary>
        public static string ManageViewChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ManageViewChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змініть пароль.
        /// </summary>
        public static string ManageViewChangeYourPassword {
            get {
                return ResourceManager.GetString("ManageViewChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string ManageViewPassword {
            get {
                return ResourceManager.GetString("ManageViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string ManageViewSettings {
            get {
                return ResourceManager.GetString("ManageViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медичний код.
        /// </summary>
        public static string MedicalCode {
            get {
                return ResourceManager.GetString("MedicalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to med.ua.
        /// </summary>
        public static string MedUATitle {
            get {
                return ResourceManager.GetString("MedUATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна.
        /// </summary>
        public static string NewEntryViewCancel {
            get {
                return ResourceManager.GetString("NewEntryViewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string NewEntryViewSave {
            get {
                return ResourceManager.GetString("NewEntryViewSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролі не співпадають.
        /// </summary>
        public static string PasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат паролю. Пароль має складатись хоча б з однієї цифри[0-9] або символа, хоча б однієї маленької та великої літери..
        /// </summary>
        public static string PasswordErrorFormat {
            get {
                return ResourceManager.GetString("PasswordErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати запис.
        /// </summary>
        public static string PatientHistoryFormAddEntry {
            get {
                return ResourceManager.GetString("PatientHistoryFormAddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати записи усіх лікарів.
        /// </summary>
        public static string PatientHistoryFormAllEntries {
            get {
                return ResourceManager.GetString("PatientHistoryFormAllEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас немає записів.
        /// </summary>
        public static string PatientHistoryFormEmptyHistory {
            get {
                return ResourceManager.GetString("PatientHistoryFormEmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої записи.
        /// </summary>
        public static string PatientHistoryFormMyEntries {
            get {
                return ResourceManager.GetString("PatientHistoryFormMyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія.
        /// </summary>
        public static string PatientHistoryFormTitle {
            get {
                return ResourceManager.GetString("PatientHistoryFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути картку.
        /// </summary>
        public static string PatientLayoutLookMedicalCard {
            get {
                return ResourceManager.GetString("PatientLayoutLookMedicalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останній запис.
        /// </summary>
        public static string PatientListViewModelLastDateVisit {
            get {
                return ResourceManager.GetString("PatientListViewModelLastDateVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лікарі.
        /// </summary>
        public static string PatientProfileViewModelDoctorList {
            get {
                return ResourceManager.GetString("PatientProfileViewModelDoctorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По батькові.
        /// </summary>
        public static string Patronimic {
            get {
                return ResourceManager.GetString("Patronimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місце народження.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string RegisterViewRegister {
            get {
                return ResourceManager.GetString("RegisterViewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        public static string RegisterViewTitle {
            get {
                return ResourceManager.GetString("RegisterViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запам&apos;ятати мене?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} має бути заповненим.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to увійдіть.
        /// </summary>
        public static string ResetPasswordConfirmationLink {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка, {0}..
        /// </summary>
        public static string ResetPasswordConfirmationMessageStringFormat {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationMessageStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль був успішно змінений.
        /// </summary>
        public static string ResetPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збросити.
        /// </summary>
        public static string ResetPasswordReset {
            get {
                return ResourceManager.GetString("ResetPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збросити пароль.
        /// </summary>
        public static string ResetPasswordViewResetYourPassword {
            get {
                return ResourceManager.GetString("ResetPasswordViewResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збросити пароль.
        /// </summary>
        public static string ResetPasswordViewTitle {
            get {
                return ResourceManager.GetString("ResetPasswordViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пацієнт.
        /// </summary>
        public static string SearchResultsPartialAdded {
            get {
                return ResourceManager.GetString("SearchResultsPartialAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це ви.
        /// </summary>
        public static string SearchResultsPartialItsYou {
            get {
                return ResourceManager.GetString("SearchResultsPartialItsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По вашому запиту нікого не знайдено або пошук не вдовільняє критеріям..
        /// </summary>
        public static string SearchResultsPartialNotFound {
            get {
                return ResourceManager.GetString("SearchResultsPartialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медичний код або ПІП.
        /// </summary>
        public static string SearchViewExplanation {
            get {
                return ResourceManager.GetString("SearchViewExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати більше.
        /// </summary>
        public static string ShowMoreEntriesLink {
            get {
                return ResourceManager.GetString("ShowMoreEntriesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} має бути не менше ніж {2} символів..
        /// </summary>
        public static string TheMustBeAtLeastCharactersLongStringFormat {
            get {
                return ResourceManager.GetString("TheMustBeAtLeastCharactersLongStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час народження.
        /// </summary>
        public static string TimeOfBirth {
            get {
                return ResourceManager.GetString("TimeOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль був змінений..
        /// </summary>
        public static string YouPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YouPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль був встановлений..
        /// </summary>
        public static string YouPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YouPasswordHasBeenSet", resourceCulture);
            }
        }
    }
}
