// <auto-generated />
namespace MedUA.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removeresearchfromentry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removeresearchfromentry));
        
        string IMigrationMetadata.Id
        {
            get { return "201706111430442_Remove research from entry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
